name: new_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.11
  flutter:
    sdk: flutter
  geolocator: ^7.7.1
  maps_toolkit: ^2.0.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: any
  http: ^0.13.4
  url_launcher: ^6.0.12
  mailer: ^5.0.2
  flutter_email_sender: ^5.0.2
  image_picker: ^0.8.4+4
  firebase_database: ^9.0.4


#  flutter_polyline_points: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/loading-icegif-1.gif
    - images/7db623e4514e37914168ff09f6516cec.gif
    - images/fingerprint_POSTCARD.jpg
    - images/LODING-02.jpg
    - images/LODING-01.jpg
    - images/dark-blue-blurred-abstract-background-wallpaper-vi.jpg
    - images/logos-01.png
    - images/Ofw logistic logo file-01.png
    - images/New Project (1).png
    - images/New Project (2).png
    - images/New Project.png
    - images/BenefitsofClockInAPP-BlogBanner-1200x628-1.jpg
    - images/Group 82.png
    - images/Group 79.png
    - images/Group 83.png
    - images/Mask-Group-1.png
    - images/Group 57.png
    - images/Rectangle 23.png
    - images/Group 101.jpg
    - images/Group 102.jpg
    - images/Group 94.jpg
    - images/Group-74.png
    - images/Group-73.png
    - images/Group 75 (3).png
    - images/Group 76.png
    - images/Group 75.png
    - images/Group 95.jpg
    - images/Group 96.jpg
    - images/Group 97.jpg
    - images/Group 98.jpg
    - images/Group 99.jpg
    - images/Group 100.jpg
    - images/Group 92.jpg
    - images/Group 91.jpg
    - images/Group 93 (1).jpg
    - images/Group 86.jpg
    - images/Group 87.jpg
    - images/Group 88.jpg
    - images/Group 89.jpg
    - images/Group 84.jpg
    - images/Group 85.jpg
    - images/Group 106.png
    - images/Group 107.png
    - images/Group 108.png
    - images/Group 109.png
    - images/Group 110.png
    - images/Group 111.png
    - images/Group 112.png
    - images/Group 113.png
    - images/Group 114.png
    - images/Thank You screen.png
    - images/Group 120.png
    - images/grp221.png
    - images/Group 116(1).png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
